<?php

namespace Acmtool\JBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcoountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcoountRepository extends EntityRepository
{
}
