<?php

namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
	public function findByUserName($username){
		if($username)
		{
			$cred=$this->getEntityManager()->getRepository('AcmtoolAppBundle:Creds')->findOneBy(array('login' => $username));
			return $this->getEntityManager()->getRepository('AcmtoolAppBundle:Admin')->findOneBy(array('credentials' => $cred));
		}
		else
			return null;
	}
}
