<?php

namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acmtool\AppBundle\Entity\Titles;

/**
 * CredsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredsRepository extends EntityRepository
{
	public function getUserByUsername($username)
	{
		$creds=$this->findOneBy(array('login' => $username ));
		switch ($creds->getTitle()) {
			case Titles::Admin:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:Admin")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::Developer:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:Developer")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::Customer:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:Customer")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::CustomerUser:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:CustomerUser")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::Designer:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:Designer")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::KeyAccount:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:KeyAccount")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::SystemAdmin:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:SystemAdmin")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::TeamLeader:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:TeamLeader")->findOneBy(array("credentials"=>$creds));
				break;
			case Titles::Tester:
				return $this->getEntityManager()->getRepository("AcmtoolAppBundle:Tester")->findOneBy(array("credentials"=>$creds));
				break;
			default:
				return false;
				break;
		}


	}
}