<?php
namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acmtool\AppBundle\Entity\Titles;

/**
 * CustomerUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerUserRepository extends EntityRepository
{
	public function getUsersByclient($customer)
	{
		$em=$this->getEntityManager();
		$result=$em->createQuery('select c from AcmtoolAppBundle:CustomerUser c
								WHERE c.company = :customer')
						->setParameter("customer",$customer)
                        ->getResult();
        return $result;
	}
	/*public function getUsersByKeyCustomer($customer,$start)
	{
		$em=$this->getEntityManager();
		$result=$em->createQuery('select c from AcmtoolAppBundle:CustomerUser c
								WHERE c.company = :customer')
						->setParameter("customer",$customer)
                        ->setMaxResults(ConstValues::COUNT)
                        ->setFirstResult($start)
                        ->getResult();
        return $result;
	}
	public function getCustomerUsersCount($customer)
	{
		$em=$this->getEntityManager();
		$totalcount=$em->createQuery("SELECT COUNT(c) FROM AcmtoolAppBundle:Customer c WHERE c.company = :customer")
			->setParameter("customer",$customer)
            ->getSingleScalarResult();
        return $totalcount;
	}*/
}