<?php
namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acmtool\AppBundle\Entity\Titles;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
	public function getCustomersByKeyAccount($keyaccount,$start)
	{
		$em=$this->getEntityManager();
		$result=$em->createQuery('select c from AcmtoolAppBundle:Customer c
								WHERE c.keyAccount = :keyaccount')
						->setParameter("keyaccount",$keyaccount)
                        ->setMaxResults(ConstValues::COUNT)
                        ->setFirstResult($start)
                        ->getResult();
        return $result;
	}
	public function getKeyAccountCustomersCount($keyaccount)
	{
		$em=$this->getEntityManager();
		$totalcount=$em->createQuery("SELECT COUNT(c) FROM AcmtoolAppBundle:Customer c WHERE c.keyAccount = :keyaccount")
			->setParameter("keyaccount",$keyaccount)
            ->getSingleScalarResult();
        return $totalcount;
	}
}