<?php

namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoNotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoNotifRepository extends EntityRepository
{
}
