<?php

namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeamLeaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
//For this version teamleader role is not used but we keep this for later versions,
class TeamLeaderRepository extends EntityRepository
{
}
