<?php

namespace Acmtool\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Acmtool\AppBundle\Entity\Token;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
	Private $roles=array('ROLE_ADMIN','ROLE_CUSTOMER','ROLE_CUSER','ROLE_DESIGNER','ROLE_DEVELOPER','ROLE_KEYACCOUNT','ROLE_SYSADMIN','ROLE_TEAMLEADER','ROLE_TESTER' );
	
	public function findUserByToken(Token $token)
	{
		if(!in_array($token->getUserrole(), $this->roles))
			return false;
		else
			switch ($token->getUserrole()) {
				case 'ROLE_ADMIN':
					return $token->getAdmin();
					break;
				case 'ROLE_CUSTOMER':
					return $token->getCustomer();
					break;
				case 'ROLE_CUSER':
					return $token->getCustomeruser();
					break;
				case 'ROLE_DESIGNER':
					return $token->getDesigner();
					break;
				case 'ROLE_DEVELOPER':
					return $token->getDeveloper();
					break;
				case 'ROLE_KEYACCOUNT':
					return $token->getKeyaccount();
					break;
				case 'ROLE_SYSADMIN':
					return $token->getSystemadmin();
					break;
				case 'ROLE_TEAMLEADER':
					return $token->getTeamleader();
					break;
				case 'ROLE_TESTER':
					return $token->getTester();
					break;	
				default:
					return false;
					break;
			}

	}
}
