acmtool_j:
    resource: "@AcmtoolJBundle/Resources/config/routing.yml"
    prefix:   /api

acmtool_app:
    resource: "@AcmtoolAppBundle/Resources/config/routing.yml"
    prefix:   /api
acmtool_notification:
    resource: "@AcmtoolAppBundle/Resources/config/notificationrouting.yml"
    prefix:   /notification