security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Acmtool\AppBundle\Entity\Creds: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory,admin_provider,customer_provider,customerUser_provider,developer_provider,designer_provider,keyAccount_provider,sysAdmin_provider,teamLeader_provider,tester_provider]
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        admin_provider:
            entity: {class: AcmtoolAppBundle:Admin}
        customer_provider:
            entity: {class: AcmtoolAppBundle:Customer}
        customerUser_provider:
            entity: {class: AcmtoolAppBundle:CustomerUser}
        developer_provider:
            entity: {class: AcmtoolAppBundle:Developer}
        designer_provider:
            entity: {class: AcmtoolAppBundle:Designer}
        keyAccount_provider:
            entity: {class: AcmtoolAppBundle:KeyAccount}
        sysAdmin_provider:
            entity: {class: AcmtoolAppBundle:SystemAdmin}
        teamLeader_provider:
            entity: {class: AcmtoolAppBundle:TeamLeader}
        tester_provider:
            entity: {class: AcmtoolAppBundle:Tester}

    firewalls:
        api_secured:
            pattern:  ^/api/private/
            stateless:  true
            Api_Auth: true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/api/private/super/, roles: [ROLE_ADMIN] }
        - { path: ^/api/private/teamleader/, roles: [ROLE_ADMIN,ROLE_TEAMLEADER] }
        - { path: ^/api/private/developer/, roles: [ROLE_ADMIN,ROLE_DEVELOPER] }
        - { path: ^/api/private/tester/, roles: [ROLE_ADMIN,ROLE_TESTER] }
        - { path: ^/api/private/designer/, roles: [ROLE_ADMIN,ROLE_DESIGNER] }
        - { path: ^/api/private/sysadmin/, roles: [ROLE_ADMIN,ROLE_SYSADMIN] }
        - { path: ^/api/private/keyaccount/, roles: [ROLE_ADMIN,ROLE_KEYACCOUNT] }
        - { path: ^/api/private/customer/, roles: [ROLE_ADMIN,ROLE_KEYACCOUNT,ROLE_COSTUMER] }
        - { path: ^/api/private/customer/users/, roles: [ROLE_COSTUMER,ROLE_CUSER,ROLE_KEYACCOUNT] }
        - { path: ^/api/private/project/restricted/, roles: [ROLE_COSTUMER,ROLE_CUSER,ROLE_KEYACCOUNT,ROLE_ADMIN] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
