acmtool_app_homepage:
    path:     /api/private/test
    defaults: { _controller: AcmtoolAppBundle:Default:index }

_create:
    path:     /secret/once/create
    defaults: { _controller: AcmtoolAppBundle:AdminController:Create }
    requirements:
        _method: post

update:
    path:     /private/super/admin/update
    defaults: { _controller: AcmtoolAppBundle:AdminController:update }
    requirements:
        _method: put

_api_authentification:
    path:     /public/login
    defaults: { _controller: AcmtoolAppBundle:Authentification:ApiAuthentification }
    requirements:
        _method: post

_createTeamleader:
    path:     /private/super/teamleader/create
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Create }

_updateTeamleader:
    path:     /private/teamleader/update
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Update }
    requirements:
        _method: put

_deleteTeamleader:
    path:     /private/super/teamleader/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Delete }
    requirements:
        _method: delete

_listTeamleader:
    path:     /private/super/teamleader/all/{page}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:List }
    requirements:
        _method: get

_detailsTeamleader:
    path:     /private/teamleader/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Details }
    requirements:
        _method: get

_createdeveloper:
    path:     /private/super/developer/create
    defaults: { _controller: AcmtoolAppBundle:Developer:Create }
    requirements:
        _method: post

_updatedeveloper:
    path:     /private/developer/update
    defaults: { _controller: AcmtoolAppBundle:Developer:Update }
    requirements:
        _method: put

_deletedeveloper:
    path:     /private/super/developer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Delete }
    requirements:
        _method: delete

_listdeveloper:
    path:     /private/super/developer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Developer:List }
    requirements:
        _method: get

_detailsdeveloper:
    path:     /private/developer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Details }
    requirements:
        _method: get
