acmtool_app_homepage:
    path:     /api/private/test
    defaults: { _controller: AcmtoolAppBundle:Default:index }

_create:
    path:     /secret/once/create
    defaults: { _controller: AcmtoolAppBundle:AdminController:Create }
    requirements:
        _method: post

update:
    path:     /private/super/admin/update
    defaults: { _controller: AcmtoolAppBundle:AdminController:update }
    requirements:
        _method: put

_api_authentification:
    path:     /public/login
    defaults: { _controller: AcmtoolAppBundle:Authentification:ApiAuthentification }
    requirements:
        _method: post

_createTeamleader:
    path:     /private/super/teamleader/create
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Create }

_updateTeamleader:
    path:     /private/teamleader/update
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Update }
    requirements:
        _method: put

_deleteTeamleader:
    path:     /private/super/teamleader/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Delete }
    requirements:
        _method: delete

_listTeamleader:
    path:     /private/super/teamleader/all/{page}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:List }
    requirements:
        _method: get

_detailsTeamleader:
    path:     /private/teamleader/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Details }
    requirements:
        _method: get

_createdeveloper:
    path:     /private/super/developer/create
    defaults: { _controller: AcmtoolAppBundle:Developer:Create }
    requirements:
        _method: post

_updatedeveloper:
    path:     /private/developer/update
    defaults: { _controller: AcmtoolAppBundle:Developer:Update }
    requirements:
        _method: put

_deletedeveloper:
    path:     /private/super/developer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Delete }
    requirements:
        _method: delete

_listdeveloper:
    path:     /private/super/developer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Developer:List }
    requirements:
        _method: get

_detailsdeveloper:
    path:     /private/developer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Details }
    requirements:
        _method: get
_createtester:
    path:     /private/super/tester/create
    defaults: { _controller: AcmtoolAppBundle:Tester:Create }
    requirements:
        _method: post

_updatetester:
    path:     /private/tester/update
    defaults: { _controller: AcmtoolAppBundle:Tester:Update }
    requirements:
        _method: put

_deletetester:
    path:     /private/super/tester/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Tester:Delete }
    requirements:
        _method: delete

_listtester:
    path:     /private/super/tester/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Tester:List }
    requirements:
        _method: get

_detailstester:
    path:     /private/tester/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Tester:Details }
    requirements:
        _method: get
_createdesigner:
    path:     /private/super/designer/create
    defaults: { _controller: AcmtoolAppBundle:Designer:Create }
    requirements:
        _method: post

_updatedesigner:
    path:     /private/designer/update
    defaults: { _controller: AcmtoolAppBundle:Designer:Update }
    requirements:
        _method: put

_deletedesigner:
    path:     /private/super/designer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Designer:Delete }
    requirements:
        _method: delete

_listdesigner:
    path:     /private/super/designer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Designer:List }
    requirements:
        _method: get

_detailsdesigner:
    path:     /private/designer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Designer:Details }
    requirements:
        _method: get
_createsysadmin:
    path:     /private/super/sysadmin/create
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Create }
    requirements:
        _method: post

_updatesysadmin:
    path:     /private/sysadmin/update
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Update }
    requirements:
        _method: put

_deletesysadmin:
    path:     /private/super/sysadmin/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Delete }
    requirements:
        _method: delete

_listsysadmin:
    path:     /private/super/sysadmin/all/{page}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:List }
    requirements:
        _method: get

_detailssysadmin:
    path:     /private/sysadmin/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Details }
    requirements:
        _method: get
