acmtool_app_homepage:
    path:     /api/private/test
    defaults: { _controller: AcmtoolAppBundle:Default:index }

_create:
    path:     /secret/once/create
    defaults: { _controller: AcmtoolAppBundle:AdminController:Create }
    methods: [POST,OPTIONS]

update:
    path:     /private/super/admin/update
    defaults: { _controller: AcmtoolAppBundle:AdminController:update }
    methods:  [PUT,OPTIONS]

_api_authentification:
    path:     /public/login
    defaults: { _controller: AcmtoolAppBundle:Authentification:ApiAuthentification }
    methods:  [OPTIONS,POST]

_createTeamleader:
    path:     /private/super/teamleader/create
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Create }

_updateTeamleader:
    path:     /private/teamleader/update
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Update }
    methods:  [PUT,OPTIONS]

_deleteTeamleader:
    path:     /private/super/teamleader/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Delete }
    methods:  [DELETE,OPTIONS]

_listTeamleader:
    path:     /private/super/teamleader/all/{page}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:List }
    methods:  [GET,OPTIONS]

_detailsTeamleader:
    path:     /private/teamleader/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:TeamLeader:Details }
    methods:  [GET,OPTIONS]

_createdeveloper:
    path:     /private/super/developer/create
    defaults: { _controller: AcmtoolAppBundle:Developer:Create }
    methods:  [POST,OPTIONS]

_updatedeveloper:
    path:     /private/developer/update
    defaults: { _controller: AcmtoolAppBundle:Developer:Update }
    methods:  [PUT,OPTIONS]

_deletedeveloper:
    path:     /private/super/developer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Delete }
    methods:  [DELETE,OPTIONS]

_listdeveloper:
    path:     /private/super/developer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Developer:List }
    methods:  [GET,OPTIONS]

_detailsdeveloper:
    path:     /private/developer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Developer:Details }
    methods:  [GET,OPTIONS]
_createtester:
    path:     /private/super/tester/create
    defaults: { _controller: AcmtoolAppBundle:Tester:Create }
    methods: [POST,OPTIONS]

_updatetester:
    path:     /private/tester/update
    defaults: { _controller: AcmtoolAppBundle:Tester:Update }
    methods: [PUT,OPTIONS]

_deletetester:
    path:     /private/super/tester/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Tester:Delete }
    methods: [DELETE,OPTIONS]

_listtester:
    path:     /private/super/tester/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Tester:List }
    methods: [GET,OPTIONS]

_detailstester:
    path:     /private/tester/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Tester:Details }
    methods: [GET,OPTIONS]
_createdesigner:
    path:     /private/super/designer/create
    defaults: { _controller: AcmtoolAppBundle:Designer:Create }
    methods: [POST,OPTIONS]

_updatedesigner:
    path:     /private/designer/update
    defaults: { _controller: AcmtoolAppBundle:Designer:Update }
    methods: [PUT,OPTIONS]

_deletedesigner:
    path:     /private/super/designer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Designer:Delete }
    methods: [DELETE,OPTIONS]

_listdesigner:
    path:     /private/super/designer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Designer:List }
    methods: [GET,OPTIONS]

_detailsdesigner:
    path:     /private/designer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Designer:Details }
    methods: [GET,OPTIONS]
_createsysadmin:
    path:     /private/super/sysadmin/create
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Create }
    methods: [POST,OPTIONS]

_updatesysadmin:
    path:     /private/sysadmin/update
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Update }
    methods: [PUT,OPTIONS]

_deletesysadmin:
    path:     /private/super/sysadmin/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Delete }
    methods: [DELETE,OPTIONS]

_listsysadmin:
    path:     /private/super/sysadmin/all/{page}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:List }
    methods: [GET,OPTIONS]

_detailssysadmin:
    path:     /private/sysadmin/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:SystemAdmin:Details }
    methods: [GET,OPTIONS]
_createkeyaccount:
    path:     /private/super/keyaccount/create
    defaults: { _controller: AcmtoolAppBundle:KeyAccount:Create }
    methods: [POST,OPTIONS]

_updatekeyaccount:
    path:     /private/keyaccount/update
    defaults: { _controller: AcmtoolAppBundle:KeyAccount:Update }
    methods: [PUT,OPTIONS]

_deletekeyaccount:
    path:     /private/super/keyaccount/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:KeyAccount:Delete }
    methods: [DELETE,OPTIONS]

_listkeyaccount:
    path:     /private/super/keyaccount/all/{page}
    defaults: { _controller: AcmtoolAppBundle:KeyAccount:List }
    methods: [GET,OPTIONS]

_detailskeyaccount:
    path:     /private/keyaccount/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:KeyAccount:Details }
    methods: [GET,OPTIONS]
_createcustomer:
    path:     /private/keyaccount/customer/create
    defaults: { _controller: AcmtoolAppBundle:Customer:Create }
    methods: [POST,OPTIONS]
_updatecustomer:
    path:     /private/customer/update
    defaults: { _controller: AcmtoolAppBundle:Customer:Update }
    methods: [PUT,OPTIONS]
_deletecustomer:
    path:     /private/keyaccount/customer/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Customer:Delete }
    methods: [DELETE,OPTIONS]
_listcustomer:
    path:     /private/keyaccount/customer/all/{page}
    defaults: { _controller: AcmtoolAppBundle:Customer:List }
    methods: [GET,OPTIONS]
_detailscustomer:
    path:     /private/customer/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Customer:Details }
    methods: [GET,OPTIONS]
_createcustomeruser:
    path:     /private/customer/users/create
    defaults: { _controller: AcmtoolAppBundle:CustomerUser:Create }
    methods: [POST,OPTIONS]
_updatecustomeruser:
    path:     /private/customer/users/update
    defaults: { _controller: AcmtoolAppBundle:CustomerUser:Update }
    methods: [PUT,OPTIONS]
_deletecustomeruser:
    path:     /private/customer/users/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:CustomerUser:Delete }
    methods: [DELETE,OPTIONS]
_listcustomeruser:
    path:     /private/customer/users/all/{page}
    defaults: { _controller: AcmtoolAppBundle:CustomerUser:List }
    methods: [GET,OPTIONS]
_detailscustomeruser:
    path:     /private/customer/users/profile/{id}
    defaults: { _controller: AcmtoolAppBundle:Customer:Details }
    methods: [GET,OPTIONS]
_createproject:
    path:     /private/project/restricted/create
    defaults: { _controller: AcmtoolAppBundle:Project:create }
    methods: [POST,OPTIONS]
_updateproject:
    path:     /private/project/restricted/update
    defaults: { _controller: AcmtoolAppBundle:Project:update }
    methods: [PUT,OPTIONS]
_deleteproject:
    path:     /private/project/restricted/delete/{id}
    defaults: { _controller: AcmtoolAppBundle:Project:delete }
    methods: [DELETE,OPTIONS]
_listprojects:
    path:     /private/project/restricted/list/{page}/{state}
    defaults: { _controller: AcmtoolAppBundle:Project:list }
    methods: [GET,OPTIONS]
_detailscustomeruser:
    path:     /private/project/restricted/details/{id}
    defaults: { _controller: AcmtoolAppBundle:Project:details }
    methods: [GET,OPTIONS]
_assignteamleadertoproject:
    path:     /private/super/project/teamleader/assign
    defaults: { _controller: AcmtoolAppBundle:Project:assignTeamLeader }
    methods: [POST,OPTIONS]
_adddevelopertoproject:
    path:     /private/teamleader/project/developer/add
    defaults: { _controller: AcmtoolAppBundle:Project:addDeveloper }
    methods: [POST,OPTIONS]
_adddesigneroproject:
    path:     /private/teamleader/project/designer/add
    defaults: { _controller: AcmtoolAppBundle:Project:addDesigner }
    methods: [POST,OPTIONS]
_addtesteroproject:
    path:     /private/teamleader/project/tester/add
    defaults: { _controller: AcmtoolAppBundle:Project:addTester }
    methods: [POST,OPTIONS]
_addsysadminoproject:
    path:     /private/teamleader/project/sysadmin/add
    defaults: { _controller: AcmtoolAppBundle:Project:addSysadmin }
    methods: [POST,OPTIONS]
_deletedeveloperfromproject:
    path:     /private/teamleader/project/developer/delete
    defaults: { _controller: AcmtoolAppBundle:Project:deleteDeveloper }
    methods: [POST,OPTIONS]
_deletedesignerfromproject:
    path:     /private/teamleader/project/designer/delete
    defaults: { _controller: AcmtoolAppBundle:Project:deleteDesigner }
    methods: [POST,OPTIONS]
_deletetesterfromproject:
    path:     /private/teamleader/project/tester/delete
    defaults: { _controller: AcmtoolAppBundle:Project:deleteTester }
    methods: [POST,OPTIONS]
_deletesysadminfromproject:
    path:     /private/teamleader/project/sysadmin/delete
    defaults: { _controller: AcmtoolAppBundle:Project:deleteSysadmin }
    methods: [POST,OPTIONS]
_addprojectconfig:
    path:     /private/project/restricted/config/create
    defaults: { _controller: AcmtoolAppBundle:ProjectConfig:create }
    methods: [POST,OPTIONS]
_updateprojectconfig:
    path:     /private/project/restricted/config/update
    defaults: { _controller: AcmtoolAppBundle:ProjectConfig:update }
    methods: [PUT,OPTIONS]
_projectconfigdetails:
    path:     /private/project/restricted/config/detail/{project_id}
    defaults: { _controller: AcmtoolAppBundle:ProjectConfig:getProjectConfig }
    methods: [GET,OPTIONS]
_deleteprojectconfig:
    path:     /private/project/restricted/config/delete
    defaults: { _controller: AcmtoolAppBundle:ProjectConfig:delete }
    methods: [DELETE,OPTIONS]
_allteammemebrs:
    path:     /private/team/all
    defaults: { _controller: AcmtoolAppBundle:Team:getAllTeamMmebers }
    methods: [GET,OPTIONS]
_uploadteamphoto:
    path:     /private/team/upload/photo/{id}/{role}
    defaults: { _controller: AcmtoolAppBundle:Team:uploadPhoto }
    methods: [POST,OPTIONS]
_uploadcuserphoto:
    path:     /private/customer/users/upload/photo/{id}
    defaults: { _controller: AcmtoolAppBundle:CustomerUser:uploadPhoto }
    methods: [POST,OPTIONS]