parameters:
#    acmtool_app.example.class: Acmtool\AppBundle\Example

services:
#    acmtool_app.example:
#        class: %acmtool_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
