parameters:
#    acmtool_app.example.class: Acmtool\AppBundle\Example
    acmtool_app.apiauth.provider.class: Acmtool\AppBundle\firewall\apiauth\ApiAuthProvider
    acmtool_app.apiauth.listener.class: Acmtool\AppBundle\firewall\apiauth\ApiTokenListener
    acmtool_app.authentification.class: Acmtool\AppBundle\DependencyInjection\AuthentificationService
    acmtool_app.validation.json.class: Acmtool\AppBundle\DependencyInjection\JsonValidatorService

services:
#    acmtool_app.example:
#        class: %acmtool_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    apiauth.security.authentication.provider:
     class:  '%acmtool_app.apiauth.provider.class%'
     arguments: ['@doctrine']

    apiauth.security.authentication.listener:
     class:  '%acmtool_app.apiauth.listener.class%'
     arguments: [@security.context, @security.authentication.manager]
    acmtool_app.authentication:
     class:  '%acmtool_app.authentification.class%'
     arguments: [@doctrine, @security.encoder_factory,@form.csrf_provider]
    acmtool_app.validation.json:
     class:  '%acmtool_app.validation.json.class%'